apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  labels:
    app: workbridgewayauth
data:
  PORT : "3000"
  ENV : "production"
  MONGO_URL : "mongodb+srv://sharoonkp:test123@cluster0.9aonsgn.mongodb.net/workbridgeway-auth?retryWrites=true&w=majority"
  RABBITMQ_URL : "amqps://zyppsoza:hej41p9ErgF0o1rT1VV-zd8gN_Gk0s5e@fly.rmq.cloudamqp.com/zyppsoza"
  MAILER_PASSWORD : "iqtyaldszzgoweap"
  MAILER_EMAIL :  "ecommerce1419@gmail.com"
  JWT_SECRET : "jsonwebsecret"
  