apiVersion: apps/v1
kind: Deployment
metadata:
  name: workbridgewayauth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workbridgewayauth
  template:
    metadata:
      labels:
        app: workbridgewayauth
    spec:
      containers:
      - name: workbridgewayauth
        image: sharoonkp/workbridgewayauth:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: auth-config 
---
apiVersion: v1
kind: Service
metadata:
  name: workbridgewayauth
spec:
  selector:
    app: workbridgewayauth
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000