apiVersion: apps/v1
kind: Deployment
metadata:
  name: workbridgewaychat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workbridgewaychat
  template:
    metadata:
      labels:
        app: workbridgewaychat
    spec:
      containers:
      - name: workbridgewaychat
        image: sharoonkp/workbridgewaychat:latest
        ports:
        - containerPort: 3004
        envFrom:
        - configMapRef:
            name: chat-config 
---
apiVersion: v1
kind: Service
metadata:
  name: workbridgewaychat
spec:
  selector:
    app: workbridgewaychat
  ports:
  - protocol: TCP
    port: 3004
    targetPort: 3004 
