apiVersion: apps/v1
kind: Deployment
metadata:
  name: workbridgewaycompany
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workbridgewaycompany
  template:
    metadata:
      labels:
        app: workbridgewaycompany
    spec:
      containers:
      - name: workbridgewaycompany
        image: sharoonkp/workbridgewaycompany:latest
        ports:
        - containerPort: 3002
        envFrom:
        - configMapRef:
            name: company-config
---
apiVersion: v1
kind: Service
metadata:
  name: workbridgewaycompany
spec:
  selector:
    app: workbridgewaycompany
  ports:
  - protocol: TCP
    port: 3002
    targetPort: 3002