apiVersion: apps/v1
kind: Deployment
metadata:
  name: workbridgewayemployee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workbridgewayemployee
  template:
    metadata:
      labels:
        app: workbridgewayemployee
    spec:
      containers:
      - name: workbridgewayemployee
        image: sharoonkp/workbridgewayemployee:latest
        ports:
        - containerPort: 3003
        envFrom:
        - configMapRef:
            name: employee-config
---
apiVersion: v1
kind: Service
metadata:
  name: workbridgewayemployee
spec:
  selector:
    app: workbridgewayemployee
  ports:
  - protocol: TCP
    port: 3003
    targetPort: 3003