apiVersion: apps/v1
kind: Deployment
metadata:
  name: workbridgewaynotification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workbridgewaynotification
  template:
    metadata:
      labels:
        app: workbridgewaynotification
    spec:
      containers:
      - name: workbridgewaynotification
        image: sharoonkp/workbridgewaynotification:latest
        resources:
          limits:
            cpu: "0.5"
            memory: "256Mi"
        envFrom:
        - configMapRef:
            name: notification-config