apiVersion: apps/v1
kind: Deployment
metadata:
  name: workbridgewayuser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workbridgewayuser
  template:
    metadata:
      labels:
        app: workbridgewayuser
    spec:
      containers:
      - name: workbridgewayuser
        image: sharoonkp/workbridgewayuser:latest
        ports:
        - containerPort: 3001
        envFrom:
        - configMapRef:
            name: user-config 
---
apiVersion: v1
kind: Service
metadata:
  name: workbridgewayuser
spec:
  selector:
    app: workbridgewayuser
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001