import {
 postJob,
 getAllCompanyJobs,
 updateJobStatus,
 getJobById,
 editJob,
 getAlljobs,
 getJobDetailsById,
 applyForJob,
 findUserInApplicants,
 getUserApplications,
 updateApplicantStatus,
 getUserPreferredJobs,
 findAllExpiredJobs,
 updateJobExpiryStatus,
 scheduleInterviewForUser,
} from "./jobRepo";

export default {
 postJob,
 getAllCompanyJobs,
 updateJobStatus,
 getJobById,
 editJob,
 getAlljobs,
 getJobDetailsById,
 applyForJob,
 findUserInApplicants,
 getUserApplications,
 updateApplicantStatus,
 getUserPreferredJobs,
 findAllExpiredJobs,
 updateJobExpiryStatus,
 scheduleInterviewForUser,
};
